package cli

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"reflect"

	"github.com/mpm/projectsetup/internal/config"
	"github.com/mpm/projectsetup/internal/generate"
)

func runUpgrade(root string, args []string, stdout, stderr io.Writer) error {
	flags := flag.NewFlagSet("projectsetup upgrade", flag.ContinueOnError)
	flags.SetOutput(stderr)
	aiValue := flags.String("ai", "", "replace AI selection with comma-separated opencode, claude, codex; or none")
	if err := flags.Parse(args); err != nil {
		if err == flag.ErrHelp {
			return nil
		}
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("upgrade does not accept positional arguments")
	}

	tools, err := resolveAITools(*aiValue, flags)
	if err != nil {
		return err
	}

	path := filepath.Join(root, ".devcontainer", "projectsetup.json")
	file, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open generated manifest %q: %w", path, err)
	}
	manifest, readErr := config.ReadManifest(file)
	closeErr := file.Close()
	if readErr != nil {
		return fmt.Errorf("read generated manifest %q: %w", path, readErr)
	}
	if closeErr != nil {
		return fmt.Errorf("close generated manifest %q: %w", path, closeErr)
	}
	if manifest.GeneratedBy != "projectsetup" {
		return fmt.Errorf("refusing to upgrade %q because it is not recognized as generated by projectsetup", filepath.Dir(path))
	}
	if manifest.SchemaVersion != config.SchemaVersion {
		return fmt.Errorf("cannot upgrade schemaVersion %d; this version supports schemaVersion %d", manifest.SchemaVersion, config.SchemaVersion)
	}

	if err := config.ValidateProjectName(manifest.ProjectName); err != nil {
		return fmt.Errorf("refusing to upgrade %q: manifest projectName: %w; upgrade does not rename projects, regenerate with projectsetup init --force --name NAME", filepath.Dir(path), err)
	}

	input := config.Input{
		Root:            root,
		ProjectName:     manifest.ProjectName,
		Preset:          manifest.Preset,
		Database:        manifest.Database,
		AITools:         manifest.AITools,
		PackageManager:  manifest.PackageManager,
		LanguageVersion: manifest.LanguageVersion,
		PostgresVersion: manifest.PostgresVersion,
		Ports:           manifest.Ports,
		SystemPackages:  manifest.SystemPackages,
	}
	cfg, err := config.Normalize(input)
	if err != nil {
		return fmt.Errorf("normalize generated manifest %q: %w", path, err)
	}
	if !reflect.DeepEqual(config.NewManifest(cfg), manifest) {
		return fmt.Errorf("refusing to upgrade %q because its manifest values are not normalized", filepath.Dir(path))
	}
	if tools != nil {
		input.AITools = tools
		cfg, err = config.Normalize(input)
		if err != nil {
			return fmt.Errorf("normalize requested AI selection: %w", err)
		}
	}
	if err := generate.Write(root, cfg, true); err != nil {
		return fmt.Errorf("upgrade generated configuration: %w", err)
	}
	_, err = fmt.Fprintf(stdout, "Upgraded .devcontainer for %s (%s). Recreate the container to apply mount or environment changes.\n", cfg.ProjectName, cfg.Preset)
	return err
}
