package cli

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/mpm/projectsetup/internal/config"
	"github.com/mpm/projectsetup/internal/generate"
	"github.com/mpm/projectsetup/internal/presets"
)

func runUpgrade(root string, args []string, stdout, stderr io.Writer) error {
	flags := flag.NewFlagSet("projectsetup upgrade", flag.ContinueOnError)
	flags.SetOutput(stderr)
	aiValue := flags.String("ai", "", "replace AI selection with comma-separated opencode, claude, codex; or none")
	refresh := flags.Bool("refresh-presets", false, "use the current built-in and user definitions instead of the project copies")
	if err := flags.Parse(args); err != nil {
		if err == flag.ErrHelp {
			return nil
		}
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("upgrade does not accept positional arguments")
	}

	tools, err := resolveAITools(*aiValue, flags)
	if err != nil {
		return err
	}

	devDir := filepath.Join(root, ".devcontainer")
	path := filepath.Join(devDir, "projectsetup.json")
	file, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open generated manifest %q: %w", path, err)
	}
	manifest, readErr := config.ReadManifest(file)
	closeErr := file.Close()
	if readErr != nil {
		return fmt.Errorf("read generated manifest %q: %w", path, readErr)
	}
	if closeErr != nil {
		return fmt.Errorf("close generated manifest %q: %w", path, closeErr)
	}
	if manifest.GeneratedBy != config.GeneratedBy {
		return fmt.Errorf("refusing to upgrade %q because it is not recognized as generated by projectsetup", devDir)
	}

	if err := config.ValidateProjectName(manifest.ProjectName); err != nil {
		return fmt.Errorf("refusing to upgrade %q: manifest projectName: %w; upgrade does not rename projects, regenerate with projectsetup init --force --name NAME", devDir, err)
	}

	// Schema 1 manifests predate the project copies and used the built-ins.
	registry := presets.Builtin()
	if manifest.SchemaVersion != 1 {
		if registry, err = presets.LoadProject(filepath.Join(devDir, config.PresetsDir), manifest.Refs()); err != nil {
			return fmt.Errorf("load recorded definitions: %w", err)
		}
	}
	input := manifest.Input(root, registry)
	cfg, err := config.Normalize(input)
	if err != nil {
		return fmt.Errorf("normalize generated manifest %q: %w", path, err)
	}
	if !config.SameSelection(config.NewManifest(cfg), manifest) {
		return fmt.Errorf("refusing to upgrade %q because its manifest values are not normalized", devDir)
	}
	if *refresh || tools != nil {
		if *refresh {
			if input.Registry, err = presets.Load(); err != nil {
				return fmt.Errorf("load preset definitions: %w", err)
			}
		}
		if tools != nil {
			input.AITools = tools
		}
		if cfg, err = config.Normalize(input); err != nil {
			return fmt.Errorf("normalize upgraded configuration: %w", err)
		}
	}
	if err := generate.Write(root, cfg, true); err != nil {
		return fmt.Errorf("upgrade generated configuration: %w", err)
	}
	_, err = fmt.Fprintf(stdout, "Upgraded .devcontainer for %s (%s). Recreate the container to apply mount or environment changes.\n", cfg.ProjectName, cfg.Preset)
	return err
}
