#!/usr/bin/env bash
# Generated by projectsetup. Edit projectsetup.json and regenerate instead of editing this file.
set -euo pipefail

[[ -w "/workspaces/fixed-app" && -x "/workspaces/fixed-app" ]] || {
  echo 'projectsetup: workspace bind source is not writable/searchable by fixed vscode IDs; repair the project directory on the host or select a matching image' >&2
  exit 1
}
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
"${script_dir}/install-ai-tools.sh" 

