#!/usr/bin/env bash
# Generated by projectsetup. This canonical installer is shared by every preset.
set -euo pipefail

fail() {
  printf 'projectsetup AI installer: %s\n' "$*" >&2
  exit 1
}

ensure_writable() {
  local path="$1"
  mkdir -p "$path" 2>/dev/null || sudo mkdir -p "$path"
  if [[ ! -w "$path" ]]; then
    sudo chown -R "$(id -u):$(id -g)" "$path"
  fi
  [[ -w "$path" ]] || fail "$path is not writable; check the host bind-mount source ownership"
}

update=false
if [[ "${1:-}" == --update ]]; then
  update=true
  shift
  (( $# > 0 )) || fail "--update requires at least one tool: opencode, claude, codex"
fi
# Reject bad selections before installing or updating any tool.
for tool in "$@"; do
  case "$tool" in
    opencode|claude|codex) ;;
    *) fail "unsupported AI tool: $tool; use [--update] opencode|claude|codex ..." ;;
  esac
done

# Shared Codex data must already be owned by the host user. Never recursively
# change ownership of credentials/history to repair container parent directories.
require_writable() {
  mkdir -p "$1" || fail "cannot create $1; check the host bind-mount source ownership"
  [[ -w "$1" ]] || fail "$1 is not writable; fix the host bind-mount source ownership"
}

install_codex() (
  local installer
  installer="$(mktemp)" || fail "cannot create temporary Codex installer"
  trap 'rm -f "$installer"' EXIT
  curl -fsSL https://chatgpt.com/codex/install.sh -o "$installer" || fail "download Codex installer failed"
  # Keep the installation separate from the real CODEX_HOME and its credentials.
  CODEX_HOME="$codex_install" CODEX_INSTALL_DIR="$codex_install/bin" \
    CODEX_NON_INTERACTIVE=1 PATH="$codex_install/bin:$PATH" sh "$installer" ||
    fail "Codex installer failed"
)

# The official installer writes absolute symlinks. Use relative links within
# the mounted installation so host and container home paths can differ.
relocate_codex() {
  local standalone="$codex_install/packages/standalone"
  local target release command_target
  target="$(readlink "$standalone/current")" || fail "Codex installer did not create packages/standalone/current"
  release="${target##*/}"
  [[ -n "$release" && "$release" != . && "$release" != .. && -d "$standalone/releases/$release" ]] ||
    fail "Codex installer created an unexpected release link: $target"
  ln -s "releases/$release" "$standalone/.current-projectsetup-$$"
  mv -Tf "$standalone/.current-projectsetup-$$" "$standalone/current"
  if [[ -x "$standalone/current/bin/codex" ]]; then
    command_target="../packages/standalone/current/bin/codex"
  elif [[ -x "$standalone/current/codex" ]]; then
    command_target="../packages/standalone/current/codex"
  else
    fail "Codex installer did not create an executable release"
  fi
  ln -s "$command_target" "$codex_install/bin/.codex-projectsetup-$$"
  mv -Tf "$codex_install/bin/.codex-projectsetup-$$" "$codex_install/bin/codex"
}

ensure_writable "$HOME/.local"
ensure_writable "$HOME/.local/bin"
ensure_writable "$HOME/.local/state"

for tool in "$@"; do
  case "$tool" in
    opencode)
      ensure_writable "$HOME/.config/opencode"
      ensure_writable "$HOME/.local/share/opencode"
      ensure_writable "$HOME/.opencode"
      ensure_writable "$HOME/.cache/opencode"
      opencode_binary="$HOME/.opencode/bin/opencode"
      if previous="$("$opencode_binary" --version 2>/dev/null)"; then
        if "$update"; then
          printf 'Updating OpenCode (previous: %s)\n' "$previous"
          "$opencode_binary" upgrade --method curl || fail "OpenCode update failed; retry --update opencode"
        fi
      else
        command -v curl >/dev/null 2>&1 || fail "curl is required to install OpenCode"
        curl -fsSL https://opencode.ai/install | bash || fail "OpenCode installer failed"
      fi
      [[ -x "$HOME/.opencode/bin/opencode" ]] || fail "OpenCode installer did not create ~/.opencode/bin/opencode"
      ln -sfn "$HOME/.opencode/bin/opencode" "$HOME/.local/bin/opencode"
      "$opencode_binary" --version || fail "OpenCode installation is not executable; check host/container platform compatibility"
      ;;
    claude)
      ensure_writable "$HOME/.claude"
      ensure_writable "$HOME/.local/share/claude"
      export CLAUDE_CONFIG_DIR="$HOME/.claude"
      claude_binary="$(find "$HOME/.local/share/claude/versions" -mindepth 1 -maxdepth 1 -type f -executable -printf '%T@ %p\n' 2>/dev/null | sort -nr | cut -d' ' -f2- | sed -n '1p' || true)"
      if [[ -z "$claude_binary" ]] || ! "$claude_binary" --version >/dev/null 2>&1; then
        command -v curl >/dev/null 2>&1 || fail "curl is required to install Claude Code"
        curl -fsSL https://claude.ai/install.sh | bash || fail "Claude Code installer failed"
        claude_binary="$(find "$HOME/.local/share/claude/versions" -mindepth 1 -maxdepth 1 -type f -executable -printf '%T@ %p\n' 2>/dev/null | sort -nr | cut -d' ' -f2- | sed -n '1p' || true)"
      fi
      [[ -n "$claude_binary" ]] || fail "Claude installer did not create a persisted version binary"
      ln -sfn "$claude_binary" "$HOME/.local/bin/claude"
      "$HOME/.local/bin/claude" --version || fail "Claude Code installation is not executable"
      if "$update"; then
        "$HOME/.local/bin/claude" update || fail "Claude Code update failed"
        claude_binary="$(find "$HOME/.local/share/claude/versions" -mindepth 1 -maxdepth 1 -type f -executable -printf '%T@ %p\n' 2>/dev/null | sort -nr | cut -d' ' -f2- | sed -n '1p' || true)"
        [[ -n "$claude_binary" ]] || fail "Claude update did not leave a persisted version binary"
        ln -sfn "$claude_binary" "$HOME/.local/bin/claude"
        "$HOME/.local/bin/claude" --version || fail "Updated Claude Code is not executable"
      fi
      ;;
    codex)
      codex_install="$HOME/.local/share/codex"
      require_writable "${CODEX_HOME:-$HOME/.codex}"
      require_writable "$codex_install"
      command -v flock >/dev/null 2>&1 || fail "flock (util-linux) is required to serialize shared Codex updates"
      exec {codex_lock}>"$codex_install/.projectsetup-install.lock"
      flock -x "$codex_lock" || fail "cannot lock shared Codex installation"
      codex_binary="$codex_install/bin/codex"
      if [[ -e "$codex_binary" || -L "$codex_binary" ]]; then
        previous="$("$codex_binary" --version 2>/dev/null)" ||
          fail "shared Codex binary $codex_binary cannot run; host and container must use compatible Linux/CPU architectures and relative installation links. Repair the shared installation on the host"
        printf 'Codex: %s\n' "$previous"
      fi
      if "$update" || [[ ! -e "$codex_binary" ]]; then
        install_codex
        relocate_codex
      fi
      [[ -x "$codex_binary" ]] || fail "Codex installer did not create $codex_binary"
      ln -sfn "../share/codex/bin/codex" "$HOME/.local/bin/codex"
      "$codex_binary" --version || fail "shared Codex installation is not executable; check host/container platform compatibility"
      flock -u "$codex_lock"
      exec {codex_lock}>&-
      ;;
    *)
      fail "unsupported AI tool: $tool"
      ;;
  esac
done
