package generate

import (
	"bytes"
	"fmt"
	"slices"
	"strconv"

	"github.com/mpm/projectsetup/internal/config"
	"github.com/mpm/projectsetup/internal/presets"
	yaml "go.yaml.in/yaml/v3"
)

const generatedYAMLHeader = "# Generated by projectsetup. Edit projectsetup.json and regenerate instead of editing this file.\n"

// renderCompose builds compose.yaml as YAML nodes so that values from
// definitions are always quoted correctly and keys keep a stable order.
func renderCompose(cfg config.Config, resolved presets.Resolved) ([]byte, error) {
	appVolumes := sequence(str("..:" + cfg.Workspace.ContainerPath))
	for _, tool := range cfg.AITools {
		if tool == config.AIToolCodex {
			appVolumes.Content = append(appVolumes.Content, mapping(
				str("type"), str("bind"),
				str("source"), str(config.CodexStateSource),
				str("target"), str(cfg.Container.Home+"/.codex"),
			))
		}
	}
	app := mapping(
		str("build"), mapping(str("context"), str(".."), str("dockerfile"), str(".devcontainer/Dockerfile")),
		str("command"), str("sleep infinity"),
		str("user"), str(cfg.Container.User),
		str("volumes"), appVolumes,
	)

	names := sortedKeys(resolved.Services)
	dependsOn := mapping()
	for _, name := range names {
		if condition := resolved.Services[name].AppDependsOn; condition != "" {
			dependsOn.Content = append(dependsOn.Content, str(name), mapping(str("condition"), str(condition)))
		}
	}
	if len(dependsOn.Content) > 0 {
		app.Content = append(app.Content, str("depends_on"), dependsOn)
	}

	services := mapping(str(cfg.Container.ServiceName), app)
	var volumeNames []string
	for _, name := range names {
		service := resolved.Services[name]
		node := mapping(str("image"), str(service.Image))
		if service.Restart != "" {
			node.Content = append(node.Content, str("restart"), str(service.Restart))
		}
		if len(service.Environment) > 0 {
			environment := mapping()
			for _, key := range sortedKeys(service.Environment) {
				environment.Content = append(environment.Content, str(key), str(service.Environment[key]))
			}
			node.Content = append(node.Content, str("environment"), environment)
		}
		if check := service.Healthcheck; check != nil {
			test := sequence()
			test.Style = yaml.FlowStyle
			for _, part := range check.Test {
				test.Content = append(test.Content, str(part))
			}
			healthcheck := mapping(str("test"), test)
			if check.Interval != "" {
				healthcheck.Content = append(healthcheck.Content, str("interval"), str(check.Interval))
			}
			if check.Timeout != "" {
				healthcheck.Content = append(healthcheck.Content, str("timeout"), str(check.Timeout))
			}
			if check.Retries > 0 {
				healthcheck.Content = append(healthcheck.Content, str("retries"), &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: strconv.Itoa(check.Retries)})
			}
			node.Content = append(node.Content, str("healthcheck"), healthcheck)
		}
		if len(service.Volumes) > 0 {
			volumes := sequence()
			for _, volume := range sortedKeys(service.Volumes) {
				volumes.Content = append(volumes.Content, str(volume+":"+service.Volumes[volume]))
				volumeNames = append(volumeNames, volume)
			}
			node.Content = append(node.Content, str("volumes"), volumes)
		}
		services.Content = append(services.Content, str(name), node)
	}

	document := mapping(str("name"), str(cfg.Container.ComposeProjectName), str("services"), services)
	if len(volumeNames) > 0 {
		slices.Sort(volumeNames)
		volumes := mapping()
		for _, name := range volumeNames {
			volumes.Content = append(volumes.Content, str(name), &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!null"})
		}
		document.Content = append(document.Content, str("volumes"), volumes)
	}

	var output bytes.Buffer
	output.WriteString(generatedYAMLHeader)
	encoder := yaml.NewEncoder(&output)
	encoder.SetIndent(2)
	if err := encoder.Encode(document); err != nil {
		return nil, fmt.Errorf("render compose.yaml: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("render compose.yaml: %w", err)
	}
	return output.Bytes(), nil
}

func str(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value}
}

func mapping(content ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode, Content: content}
}

func sequence(content ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Content: content}
}

func sortedKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	return keys
}
