package generate

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mpm/projectsetup/internal/config"
	"github.com/mpm/projectsetup/internal/presets"
	"github.com/mpm/projectsetup/internal/validate"
)

const sharedImagePreset = `schema = 2
kind = "preset"
name = "shared-node"
version = "1.0.0"
description = "Fixed image consumption fixture, not a verified artifact"
[image]
base = "registry.example/team/node-toolchain:fixed"
apt = ["git", "make"]
root_run = ["install -d /opt/project"]
user_run = ["mkdir -p /home/vscode/project-cache"]
[image.preinstalled]
core_packages = ["bash", "ca-certificates", "curl", "git", "gnupg", "sudo"]
[image.preinstalled.tools.node]
version = "22.14.0"
executable = "/opt/node/bin/node"
path = ["/opt/node/bin", "/usr/bin"]
[image.preinstalled.tools.npm]
version = "10.9.2"
executable = "/opt/node/bin/npm"
path = ["/opt/node/bin"]
[image.preinstalled.tools.team-cli]
version = "release_1"
executable = "/opt/team/bin/team"
path = ["/opt/team/bin", "/home/vscode/.local/bin"]
[container]
path = ["/opt/node/bin", "/opt/project/bin", "/usr/bin"]
env = { TEAM_MODE = "development" }
[features."example.com/features/opaque:1"]
enabled = true
[setup]
script = "if [ -f package-lock.json ]; then npm ci; fi"
`

const sharedImageGH = `[image.preinstalled.tools.gh]
version = "2.67.0"
executable = "/usr/bin/gh"
path = ["/usr/bin"]
`

func sharedImageInput(t *testing.T, gh bool) config.Input {
	t.Helper()
	raw := sharedImagePreset
	if gh {
		raw += sharedImageGH
	}
	definition, err := presets.Parse([]byte(raw), "shared-node.toml")
	if err != nil {
		t.Fatal(err)
	}
	definition.Source = "user"
	addon, _ := presets.Builtin().Lookup("sqlite")
	registry, err := presets.NewRegistry(definition, addon)
	if err != nil {
		t.Fatal(err)
	}
	return config.Input{ProjectName: "shared-app", Preset: "shared-node", Addons: []string{"sqlite"}, Registry: registry, SystemPackages: []string{"curl", "jq"}}
}

func TestSharedImageGenerationAndOfflineRegeneration(t *testing.T) {
	for _, gh := range []bool{false, true} {
		t.Run(map[bool]string{false: "core gh feature", true: "image gh"}[gh], func(t *testing.T) {
			t.Setenv("HOME", t.TempDir())
			root := t.TempDir()
			input := sharedImageInput(t, gh)
			input.Root = root
			cfg, err := config.Normalize(input)
			if err != nil {
				t.Fatal(err)
			}
			if err := Write(root, cfg, false); err != nil {
				t.Fatal(err)
			}
			if diagnostics := validate.Check(root, validate.Options{CheckHostMounts: true}); validate.ErrorCount(diagnostics) != 0 {
				t.Fatalf("Check: %#v", diagnostics)
			}
			files, err := render(cfg)
			if err != nil {
				t.Fatal(err)
			}
			for _, f := range files {
				switch f.name {
				case "devcontainer.json":
					var doc devcontainerConfig
					if err := json.Unmarshal(f.data, &doc); err != nil {
						t.Fatal(err)
					}
					_, requested := doc.Features["ghcr.io/devcontainers/features/github-cli:1"]
					if requested == gh {
						t.Fatal("incorrect GitHub CLI installation choice")
					}
					if len(doc.Features["example.com/features/opaque:1"]) != 1 {
						t.Fatal("opaque feature removed")
					}
					want := "/home/vscode/.local/bin:/home/vscode/.opencode/bin:"
					if gh {
						want += "/usr/bin:/opt/node/bin:"
					} else {
						want += "/opt/node/bin:/usr/bin:"
					}
					want += "/opt/team/bin:/opt/project/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin"
					if doc.ContainerEnv["PATH"] != want {
						t.Fatalf("PATH = %q, want %q", doc.ContainerEnv["PATH"], want)
					}
				case "Dockerfile":
					for _, step := range []string{"FROM registry.example/team/node-toolchain:fixed", "git make", "libsqlite3-dev sqlite3", "curl", "jq", "install -d /opt/project", "mkdir -p /home/vscode/project-cache", "USER vscode"} {
						if !bytes.Contains(f.data, []byte(step)) {
							t.Fatalf("Dockerfile lost %q", step)
						}
					}
				case "scripts/post-create.sh":
					if !bytes.Contains(f.data, []byte("npm ci")) {
						t.Fatal("application setup removed")
					}
				}
			}
			// Ordinary upgrade must consume only the project snapshot, preserving
			// the installation choices and every generated byte/mode.
			manifestFile, err := os.Open(filepath.Join(root, directoryName, "projectsetup.json"))
			if err != nil {
				t.Fatal(err)
			}
			manifest, err := config.ReadManifest(manifestFile)
			manifestFile.Close()
			if err != nil {
				t.Fatal(err)
			}
			registry, err := presets.LoadProject(filepath.Join(root, directoryName, config.PresetsDir), manifest.Refs())
			if err != nil {
				t.Fatal(err)
			}
			restored, err := config.Normalize(manifest.Input(root, registry))
			if err != nil {
				t.Fatal(err)
			}
			if err := Write(root, restored, true); err != nil {
				t.Fatal(err)
			}
			for _, f := range files {
				path := filepath.Join(root, directoryName, f.name)
				data, err := os.ReadFile(path)
				if err != nil {
					t.Fatal(err)
				}
				info, err := os.Stat(path)
				if err != nil {
					t.Fatal(err)
				}
				if !bytes.Equal(data, f.data) || info.Mode().Perm() != f.mode {
					t.Fatalf("upgrade changed %s", f.name)
				}
			}
		})
	}
}

func TestAbsentAndEmptyPreinstalledPreserveLegacyRendering(t *testing.T) {
	for _, name := range presets.Builtin().Names(presets.KindPreset) {
		t.Run(name, func(t *testing.T) {
			builtin, _ := presets.Builtin().Lookup(name)
			cfg, err := config.Normalize(config.Input{Root: "/tmp/app", Preset: name})
			if err != nil {
				t.Fatal(err)
			}
			legacy, err := render(cfg)
			if err != nil {
				t.Fatal(err)
			}
			for _, contract := range []string{"", "\n[image.preinstalled]\n", "\n[image.preinstalled]\ncore_packages = []\ntools = {}\n"} {
				definition, err := presets.Parse([]byte(strings.Replace(string(builtin.Raw), "schema = 1", "schema = 2", 1)+contract), name+".toml")
				if err != nil {
					t.Fatal(err)
				}
				definition.Source = builtin.Source
				registry, err := presets.NewRegistry(definition)
				if err != nil {
					t.Fatal(err)
				}
				modern, err := config.Normalize(config.Input{Root: "/tmp/app", Preset: name, Registry: registry})
				if err != nil {
					t.Fatal(err)
				}
				files, err := render(modern)
				if err != nil {
					t.Fatal(err)
				}
				if len(files) != len(legacy) {
					t.Fatal("generated tree changed")
				}
				for i, file := range files {
					if file.name != legacy[i].name || file.mode != legacy[i].mode {
						t.Fatal("generated paths/modes changed")
					}
					// These source files necessarily record the explicitly adopted format/hash.
					if file.name == "projectsetup.json" || strings.HasPrefix(file.name, "presets/") {
						continue
					}
					if !bytes.Equal(file.data, legacy[i].data) {
						t.Fatalf("%s changed for absent/empty contract", file.name)
					}
				}
			}
		})
	}
}

func TestCheckRejectsImageInstallationAndPathDrift(t *testing.T) {
	for _, tt := range []struct {
		name   string
		gh     bool
		mutate func(*devcontainerConfig)
		want   string
	}{
		{"missing core gh", false, func(d *devcontainerConfig) { delete(d.Features, "ghcr.io/devcontainers/features/github-cli:1") }, "required feature"},
		{"reinstall gh", true, func(d *devcontainerConfig) {
			d.Features["ghcr.io/devcontainers/features/github-cli:99"] = map[string]any{}
		}, `reinstalls preinstalled tool "gh"`},
		{"reinstall node digest", true, func(d *devcontainerConfig) {
			d.Features["ghcr.io/devcontainers/features/node@sha256:"+strings.Repeat("a", 64)] = map[string]any{}
		}, `reinstalls preinstalled tool "node"`},
		{"missing image path", true, func(d *devcontainerConfig) {
			d.ContainerEnv["PATH"] = strings.ReplaceAll(d.ContainerEnv["PATH"], "/opt/team/bin:", "")
		}, "ordered, deduplicated"},
		{"reordered image path", true, func(d *devcontainerConfig) {
			d.ContainerEnv["PATH"] = strings.ReplaceAll(d.ContainerEnv["PATH"], "/usr/bin:/opt/node/bin", "/opt/node/bin:/usr/bin")
		}, "ordered, deduplicated"},
		{"duplicate image path", true, func(d *devcontainerConfig) { d.ContainerEnv["PATH"] += ":/opt/node/bin" }, "ordered, deduplicated"},
		{"missing explicit feature", true, func(d *devcontainerConfig) { delete(d.Features, "example.com/features/opaque:1") }, `required feature "example.com/features/opaque:1"`},
	} {
		t.Run(tt.name, func(t *testing.T) {
			t.Setenv("HOME", t.TempDir())
			root := t.TempDir()
			input := sharedImageInput(t, tt.gh)
			input.Root = root
			cfg, err := config.Normalize(input)
			if err != nil {
				t.Fatal(err)
			}
			if err := Write(root, cfg, false); err != nil {
				t.Fatal(err)
			}
			path := filepath.Join(root, directoryName, "devcontainer.json")
			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			var doc devcontainerConfig
			if err := json.Unmarshal(data, &doc); err != nil {
				t.Fatal(err)
			}
			tt.mutate(&doc)
			data, err = marshalJSON(doc)
			if err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(path, data, 0o644); err != nil {
				t.Fatal(err)
			}
			diagnostics := validate.Check(root, validate.Options{})
			for _, diagnostic := range diagnostics {
				if diagnostic.Severity == validate.Error && strings.Contains(diagnostic.Message, tt.want) {
					return
				}
			}
			t.Fatalf("missing %q error: %#v", tt.want, diagnostics)
		})
	}
}

func TestRenderRejectsConflictingImageInstallerBeforeWriting(t *testing.T) {
	root := t.TempDir()
	input := sharedImageInput(t, true)
	input.Root = root
	cfg, err := config.Normalize(input)
	if err != nil {
		t.Fatal(err)
	}
	// Guard the rendering boundary too, even if a caller bypasses normalization.
	cfg.Definitions[0].Features["ghcr.io/devcontainers/features/node:1"] = map[string]any{"version": "22.14.0"}
	if err := Write(root, cfg, false); err == nil || !strings.Contains(err.Error(), `preinstalled tool "node" conflicts`) {
		t.Fatalf("Write error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, directoryName)); !os.IsNotExist(err) {
		t.Fatalf("failed generation wrote destination: %v", err)
	}
}
