#!/usr/bin/env bash
# Generated by projectsetup. Edit projectsetup.json and regenerate instead of editing this file.
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
"${script_dir}/install-ai-tools.sh" claude opencode

case "uv" in
  uv)
    command -v uv >/dev/null 2>&1 || python -m pip install --user uv
    if [[ -f uv.lock ]]; then
      uv sync --frozen
    elif [[ -f pyproject.toml ]]; then
      uv sync
    fi
    ;;
  poetry)
    command -v poetry >/dev/null 2>&1 || python -m pip install --user poetry
    if [[ -f pyproject.toml ]]; then
      poetry install
    fi
    ;;
  pip)
    if [[ -f requirements.txt ]]; then
      python -m pip install -r requirements.txt
    fi
    if [[ -f requirements-dev.txt ]]; then
      python -m pip install -r requirements-dev.txt
    fi
    ;;
esac
