#!/usr/bin/env bash
# Generated by projectsetup. Edit projectsetup.json and regenerate instead of editing this file.
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
"${script_dir}/install-ai-tools.sh" opencode

if [[ -f package.json ]]; then
  case "npm" in
    npm)
      if [[ -f package-lock.json ]]; then
        npm ci
      fi
      ;;
    pnpm)
      corepack enable
      if [[ -f pnpm-lock.yaml ]]; then
        pnpm install --frozen-lockfile
      fi
      ;;
    yarn)
      corepack enable
      if [[ -f yarn.lock ]]; then
        yarn install --immutable || yarn install --frozen-lockfile
      fi
      ;;
  esac
fi
